services:
  claude:
    group_add:
      - "5"
      - "356"
      - "955"
      - "959"
      - "972"
      - "985"
      - "986"
      - "989"
      - "994"
      - "995"
      - "996"
      - "998"
      - "1979"
